### ISSUE TITLE
按照使用说明遇到报错

### ISSUE THREAD

**Issue by zzlTim** [Discreater/ecnu_login#2]
(base) ubuntu@ubuntu:~/ecnu_internet/ecnu_login$ ls
auth_client  ecnu_login.service.template  ecnu_login.sh  ecnu_login.timer  install.sh  README.md
(base) ubuntu@ubuntu:~/ecnu_internet/ecnu_login$ chmod +x ./install.sh
(base) ubuntu@ubuntu:~/ecnu_internet/ecnu_login$ ./install.sh
bash: ./install.sh: /bin/bash^M: bad interpreter: No such file or directory

在vim编辑器中，按下Esc键，然后输入以下命令来转换文件格式：
:set fileformat=unix

作者大大你可以在readme里加上我这个问和解决方法

**Comment by Discreater** [comment]
看起来像是换行符的问题，估计你是用windows的Git下载的，导致换行符变成 `\r\n`。我后续看看有没有更好的解决办法。

**Comment by Discreater** [comment]
我在 `.gitattributes` 里指定了文件换行符，现在 windows下应该也会强制用 `\r`，可以试一试还有没有问题。

**Comment by zzlTim** [comment]
是的，因为服务器没网，所以通过windows下载然后scp传过去的
